// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEfg5MD_VD_iHla6WR1rGfj8G_e0_0U4',
    appId: '1:43435659230:web:22ff98516aacc0eee1574f',
    messagingSenderId: '43435659230',
    projectId: 'backendtest-6e3f3',
    authDomain: 'backendtest-6e3f3.firebaseapp.com',
    storageBucket: 'backendtest-6e3f3.appspot.com',
    measurementId: 'G-VZR8J00KYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtwMFRysYXSM3b_2Dwiiy6u6Y-gfDBpU',
    appId: '1:43435659230:android:641f7012f632f55ce1574f',
    messagingSenderId: '43435659230',
    projectId: 'backendtest-6e3f3',
    storageBucket: 'backendtest-6e3f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpemML8qJdqgGxBxMTC_acdWrDaLTDu1s',
    appId: '1:43435659230:ios:d250104d09bce532e1574f',
    messagingSenderId: '43435659230',
    projectId: 'backendtest-6e3f3',
    storageBucket: 'backendtest-6e3f3.appspot.com',
    iosBundleId: 'com.tictac.wrteam.disputeresolverai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXEfg5MD_VD_iHla6WR1rGfj8G_e0_0U4',
    appId: '1:43435659230:web:6fb733211fd21ed0e1574f',
    messagingSenderId: '43435659230',
    projectId: 'backendtest-6e3f3',
    authDomain: 'backendtest-6e3f3.firebaseapp.com',
    storageBucket: 'backendtest-6e3f3.appspot.com',
    measurementId: 'G-XX61XRZVSC',
  );

}